# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "pro_micro" ]
# shield: [ "splitdb_left", "splitdb_right" ]
# include:
#   - board: pro_micro
#     shield: splitdb
#

---
include:
  - board: pro_micro
    shield: splitdb_left
  - board: pro_micro
    shield: splitdb_right
